name: Deploy reports (simples)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reports-service:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reports-service:latest

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy na EC2 (rodar container)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reports-service:latest || true
          docker stop reports-service || true
          docker rm reports-service || true
          docker run -d \
            -p 8081:5001 \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e TASKS_SERVICE_URL="http://54.233.188.129:8080" \
            -e PORT=5001 \
            -e FLASK_ENV=production \
            --name reports-service \
            ${{ secrets.DOCKERHUB_USERNAME }}/reports-service:latest
          EOF